no-permission:
  components:
    - type: 'text-display'
      content: "Sorry, it seems you donâ€™t have permission to use this command."

others-credits-view:
  components:
    - type: 'text-display'
      content: "I canâ€™t give you access to other usersâ€™ credit counts, sorry"

invalid-file-type:
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: "Ouch. I am having difficulty understanding the type of this file. It is invalid for me. If you believe it is a format I should support, contact support so it can be added."
      accessory:
        type: 'button'
        style: 'link'
        label: "Join Support Server"
        url: 'https://itsme.to/discord'

file-error:
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: |
            Oops, an error occurred while trying to read the file you sent me! Is it a valid file?
            -# Error: %error%
      accessory:
        type: 'button'
        style: 'link'
        label: "Join Support Server"
        url: 'https://itsme.to/discord'

not-enough-credits:
  components:
    - type: 'text-display'
      content: |
        Oopsie! You do not have enough credits to do this action! You need %price% credits to make it work.
        Right now, you have %user_credits% credits
    - type: 'separator'
      divider: false
      spacing: 2
    - type: 'container'
      components:
        - type: 'text-display'
          content: "### Beep-boop~ You can now buy shiny credits directly on Discord!"
        - type: 'section'
          components:
            - type: 'text-display'
              content: "Small credit boost âš¡"
          accessory:
            type: 'button'
            style: 'premium'
            sku-id: '1260276010776133782'
        - type: 'section'
          components:
            - type: 'text-display'
              content: "More credits, more fun ğŸŒŸ"
          accessory:
            type: 'button'
            style: 'premium'
            sku-id: '1260276162639167548'
        - type: 'section'
          components:
            - type: 'text-display'
              content: "Mega credit pack ğŸš€"
          accessory:
            type: 'button'
            style: 'premium'
            sku-id: '1260276278305751050'

translate-confirmation:
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: |
            Do you want me to translate `%file_name%` into `%language%` for **%price%** credits ?
            You currently have **%user_credits%** credits.
      accessory:
        type: 'button'
        style: 'success'
        emoji: 'âœ…'
        label: "Yes, translate it"
        custom-id: 'translate_confirm'

translation-started:
  components:
    - type: 'text-display'
      content: |
        Iâ€™ve started translating your file into %language%~ Please wait a moment! â³
        -# File: %file_name%, Cost: %price% credits, Mode: %mode%

translation-progress:
  components:
    - type: 'text-display'
      content: |
        Iâ€™ve already translated part of the file! Iâ€™m currently at %percent%...
        -# File: %file_name%, Cost: %price% credits, Mode: %mode%, Status: %current%/%total%

translation-finished:
  components:
    - type: 'text-display'
      content: |
        Iâ€™ve finished translating your awesome file! 

translation-success:
  ephemeral: true
  components:
    - type: 'text-display'
      content: 
        - "Hey %user_mention%, I have finished translating your file! ğŸš€"
        - "Surprise %user_mention%! Your file is now bilingual, thanks to me! ğŸ¤–"
        - "Ta-da %user_mention%! Your file's translation is ready to take on the world! ğŸŒ"
        - "Whoa! Your file just took a leap into a new linguistic dimension %user_mention%! ğŸš€"
        - "Hello %user_mention%! I've sprinkled some linguistic magic on your file. âœ¨"
        - "Alert: Your file has been successfully language-zapped %user_mention%! âš¡"
        - "Hey %user_mention%, Your file's translation adventure is complete! ğŸŒ"
        - "Eureka! %user_mention%, your file's language metamorphosis is complete! ğŸ¦‹"
        - "Hello %user_mention%! Your file just got a linguistic upgrade! ğŸ’¬"
    - type: file
      url: 'attachment://%file_name%'

translation-failed:
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: |
            Oops, an error occurred during the translation and I couldnâ€™t fix it!
            -# File: %file_name%, Cost: %price% credits, Mode: %mode%
      accessory:
        type: 'button'
        style: 'link'
        label: "Join Support Server"
        url: 'https://itsme.to/discord'

give-credits:
  components:
    - type: 'text-display'
      content: "I just gave %target_mention% %amount% credits, he now has %target_credits% credits! ğŸ"

credits:
  ephemeral: true
  components:
    - type: 'container'
      components:
        - type: 'text-display'
          content: "### You currently have %target_credits% credits! If you need more, you can buy some from the store!"
        - type: 'section'
          components:
            - type: 'text-display'
              content: "Small credit boost âš¡"
          accessory:
            type: 'button'
            style: 'premium'
            sku-id: '1260276010776133782'
        - type: 'section'
          components:
            - type: 'text-display'
              content: "More credits, more fun ğŸŒŸ"
          accessory:
            type: 'button'
            style: 'premium'
            sku-id: '1260276162639167548'
        - type: 'section'
          components:
            - type: 'text-display'
              content: "Mega credit pack ğŸš€"
          accessory:
            type: 'button'
            style: 'premium'
            sku-id: '1260276278305751050'

entitlement-consumed:
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: |
            Hello %user_mention%! Thank you so much for your purchase! You received %sku_name%, bringing you to %user_credits% credits~ 
            Don't hesitate to contact support if you have any questions or issues.
      accessory:
        type: 'button'
        style: 'link'
        label: "Join Support Server"
        url: 'https://itsme.to/discord'