no-permission:
  components:
    - type: 'text-display'
      content: "You do not have permission to use this command."

others-credits-view:
  components:
    - type: 'text-display'
      content: "You do not have permission to see others' credits."

invalid-file-type:
  components:
    - type: 'text-display'
      content: "Invalid file type. Please upload a valid file. If you believe this is an error, please contact support."

not-enough-credits:
  components:
    - type: 'text-display'
      content: "You do not have enough credits to perform this action. (%price% required, you have %user_credits%)."

translate-confirmation:
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: |
            Did you want to translate `%file_name%` in `%language%` for **%price%** credits ?
            You currently have **%user_credits%** credits.
      accessory:
        type: 'button'
        style: 'success'
        emoji: 'âœ…'
        label: "Confirm"
        custom-id: 'translate_confirm'

translation-started:
  components:
    - type: 'text-display'
      content: "Translation started! ..."

translation-progress:
  components:
    - type: 'text-display'
      content: |
        Translation in progress... %percent%
        -# (%current%/%total%) section translated

translation-finished:
  components:
    - type: 'text-display'
      content: |
        I finished translating your file!

translation-success:
  ephemeral: true
  components:
    - type: 'text-display'
      content: 
        - "Hey %user_mention%, I have finished translating your file! ğŸš€"
        - "Surprise %user_mention%! Your file is now bilingual, thanks to me! ğŸ¤–"
        - "Ta-da %user_mention%! Your file's translation is ready to take on the world! ğŸŒ"
        - "Whoa! Your file just took a leap into a new linguistic dimension %user_mention%! ğŸš€"
        - "Hello %user_mention%! I've sprinkled some linguistic magic on your file. âœ¨"
        - "Alert: Your file has been successfully language-zapped %user_mention%! âš¡"
        - "Hey %user_mention%, Your file's translation adventure is complete! ğŸŒ"
        - "Eureka! %user_mention%, your file's language metamorphosis is complete! ğŸ¦‹"
        - "Hello %user_mention%! Your file just got a linguistic upgrade! ğŸ’¬"
    - type: file
      url: 'attachment://%file_name%'

translation-failed:
  components:
    - type: 'text-display'
      content: "Translation failed. Please try again later or contact support. (Cost: %price% credits)"

give-credits:
  components:
    - type: 'text-display'
      content: "I just gave %target_mention% %amount% credits, he now has %target_credits% credits! ğŸ"

credits:
  ephemeral: true
  components:
    - type: 'section'
      components:
        - type: 'text-display'
          content: "You have %target_credits% credits."
      accessory:
        type: 'button'
        style: 'link'
        label: "Purchase more"
        url: 'https://discord.com/discovery/applications/1194260660834553877/store'

entitlement-consumed:
  components:
    - type: 'text-display'
      content: |
        Thanks %user_mention%! You have successfully purchased **%sku_name%** for **%credits%** credits.
        Your new balance is **%user_credits%** credits. Don't hesitate to contact support if you have any questions or issues.